version = 1

exclude_patterns = ["*.md", "*.yml", "*.yaml", "*.txt", "*.json"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true
